-- =========================================
-- BUSINESS PROBLEMS SOLUTIONS 
-- =========================================

/*
 1. Best-Performing Products
 Identify the 10 products that generated the highest sales revenue.
 Show the product name, total quantity sold, and total sales generated.
*/

SELECT *
FROM order_items;
SELECT *
FROM products;

-- Creating the Column Total Sales
ALTER TABLE order_items
ADD COLUMN total_sales decimal(10,2);

-- updating total sales 
UPDATE order_items
SET total_sales = quantity * price_per_unit;

-- Applying Inner Join
SELECT 
      oi.product_id,
      p.product_name,
      SUM(oi.total_sales) as total_sales,
      SUM(oi.quantity) as total_quantity
FROM order_items as oi
JOIN orders as o
	ON oi.order_id = o.order_id
JOIN products as p
	ON oi.product_id = p.product_id
GROUP BY 
      oi.product_id,
      p.product_name
ORDER BY total_sales desc
LIMIT 10;

--------------------------------------------------------------------------

/*
2. Revenue Contribution by Category

Find out how much revenue each product category generates
and what percentage of the overall revenue comes from each category.
*/

SELECT 
	 p.category_id,
     c.category_name, 
     ROUND(SUM(oi.total_sales),2) as total_sales,
	 ROUND(SUM(oi.total_sales) / 
            (
			 SELECT SUM(total_sales) 
             FROM order_items) * 100,2
            ) as percentage_contribution_by_each_category
FROM order_items as oi
JOIN products as p
	ON oi.product_id = p.product_id
JOIN category as c
	ON p.category_id = c.category_id
GROUP BY 
	 p.category_id,
     c.category_name
ORDER BY total_sales desc;

--------------------------------------------------------------------------

/*
3. Average Order Value (AOV)
 
Compute the average order value for each customer.
Include only customers with more than 5 orders.
*/

SELECT 
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) as full_name,
    ROUND(SUM(oi.total_sales) / COUNT(o.order_id),2) as avg_order_value,
    COUNT(o.order_id) as total_orders
FROM orders as o
JOIN customers as c
	ON o.customer_id = c.customer_id
JOIN order_items as oi
	ON o.order_id = oi.order_id
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name
HAVING COUNT(o.order_id) > 5;

--------------------------------------------------------------------------

/*
4. Customers with No Purchases

Find customers who have registered but never placed an order.
List customer details.
*/

SELECT *
FROM customers
WHERE customer_id NOT IN
(
 SELECT DISTINCT customer_id
 FROM orders
);
                        

-- Another Approach Using Joins
SELECT *
FROM customers as c
LEFT JOIN orders as o
	ON c.customer_id = o.customer_id
WHERE o.customer_id is NULL;

--------------------------------------------------------------------------

/*
5. Best-Selling Categories by State

Identify the best-selling product category for each state.
Include the total sales for that category within each state.
*/

SELECT *
FROM
(
	SELECT 
		 c.state,
		 cat.category_name,
		 SUM(oi.total_sales)  as total_sales,
		 RANK() OVER(PARTITION BY c.state ORDER BY SUM(oi.total_sales) desc) as rank_category_state_wise
	FROM orders as o
	JOIN customers as c
		ON o.customer_id = c.customer_id
	JOIN order_items as oi
		ON o.order_id = oi.order_id
	JOIN products as p
		ON oi.product_id = p.product_id
	JOIN category as cat
		ON p.category_id = cat.category_id
	GROUP BY
		  c.state,
		  cat.category_namE
) as ranked_state_wise
WHERE rank_category_state_wise = 1;

--------------------------------------------------------------------------

/*
6. Customer Lifetime Value (CLTV)
(CLTV means total sales value generated by that customer over all their orders in your dataset.)

Calculate the total value of orders placed by each customer over their lifetime. 
Rank customers based on their CLTV
*/

SELECT 
     c.customer_id,
     CONCAT(c.first_name ,' ' , c.last_name) as full_name,
     ROUND(SUM(oi.total_sales),2) as cltv,
     DENSE_RANK() OVER(ORDER BY ROUND(SUM(oi.total_sales),2) desc) as rank_based_on_cltv
FROM orders as o
JOIN customers as c
	ON o.customer_id = c.customer_id
JOIN order_items as oi
	ON o.order_id = oi.order_id
GROUP BY
       c.customer_id,
       CONCAT(c.first_name ,' ' , c.last_name)
ORDER BY 
       cltv DESC;
       
--------------------------------------------------------------------------

/*
7. Inventory Stock Alerts 

Query products with stock levels below a certain threshold (e.g., less than 10 units). 
Include last restock date and warehouse information.
*/

SELECT 
     i.inventory_id,
     p.product_name,
     i.stock as current_stock_left,
     i.warehouse_id,
     i.last_stock_date
FROM inventory as i
JOIN products as p
ON i.product_id = p.product_id
WHERE stock < 10;

---------------------------------------------------------------------------

/*
8. Shipping Delays

Identify orders where the shipping date is later than 3 days after the order date.
Sort the results by shipping delay, from highest to lowest.
Include customer, order details, and delivery provider.
*/

SELECT 
    o.order_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    o.order_date,
    s.shipping_date,
    s.shipping_providers,
    DATEDIFF(s.shipping_date, o.order_date) AS shipping_delays
FROM orders as o
JOIN customers as c
ON o.customer_id = c.customer_id
JOIN shipping as s
ON o.order_id = s.order_id
WHERE DATEDIFF(s.shipping_date, o.order_date) > 3
ORDER BY
      shipping_delays desc; 

---------------------------------------------------------------------------

/*
9. Payment Success Rate 

Calculate the percentage of successful payments across all orders.
Include breakdowns by payment status (e.g., failed, pending).
*/

SELECT 
     p.payment_status,
     COUNT(*) as total_count,
     ROUND(COUNT(*) / (SELECT COUNT(*) FROM payments) * 100, 2) AS percentage_of_successful_payments
FROM orders as o
JOIN payments as p
ON o.order_id = p.order_id
GROUP BY
     p.payment_status
ORDER BY
     percentage_of_successful_payments desc;

---------------------------------------------------------------------------

/*
10. Product Profit Margin

Calculate the profit margin for each product sold (difference between price and cost of goods sold).
Rank products by their profit margin, showing highest to lowest.
*/

SELECT 
     p.product_id,
     p.product_name,
     SUM(oi.total_sales - (p.cogs * oi.quantity)) as profit,
     ROUND(SUM(oi.total_sales - (p.cogs * oi.quantity)) / SUM(oi.total_sales) *100,2) as profit_margin,
     DENSE_RANK() OVER(ORDER BY SUM(oi.total_sales - (p.cogs * oi.quantity)) / SUM(oi.total_sales) *100 desc) as rank_profit_margin
FROM order_items as oi
JOIN products as p
ON oi.product_id = p.product_id
GROUP BY
      p.product_id,
      p.product_name;

---------------------------------------------------------------------------

/*
11. Most Returned Products

Query the top 10 products by the number of returns.
Display the return rate as a percentage of total units sold for each product.
*/

SELECT
     p.product_id,
	 p.product_name,
     COUNT(*) as total_orders,
     SUM(CASE
            WHEN o.order_status = 'Returned'
            THEN oi.quantity
            ELSE 0
        END) as returned_units,
	 SUM(oi.quantity) as total_units_sold,
     ROUND(SUM(CASE
                WHEN o.order_status = 'Returned'
                THEN oi.quantity
                ELSE 0
               END) / SUM(oi.quantity) * 100,2) as return_rate
FROM orders as o
JOIN order_items as oi
    ON o.order_id = oi.order_id
JOIN products as p
    ON oi.product_id = p.product_id
GROUP BY 
     p.product_id,
	 p.product_name
ORDER BY
    return_rate DESC
LIMIT 10;

---------------------------------------------------------------------------

/*
12. Top 5 customers by orders in each state

Identify the top 5 customers with the highest number of orders by each state
Include the number of orders and total sales for each customers
*/

SELECT *
FROM
(
	SELECT 
		c.state,
		CONCAT(c.first_name,' ',c.last_name) as full_name,
		COUNT(quantity) as total_orders,
		SUM(oi.total_sales) as total_sales,
		DENSE_RANK() OVER(PARTITION BY c.state ORDER BY COUNT(quantity) desc) as rank_highest_order_state
	FROM customers as c
	JOIN orders as o
	ON o.customer_id = c.customer_id
	JOIN order_items as oi
	ON o.order_id = oi.order_id
	GROUP BY
		 c.state,
		 CONCAT(c.first_name,' ',c.last_name)
	ORDER BY
		  total_orders  desc
) as ranked_table
WHERE rank_highest_order_state <= 5;

---------------------------------------------------------------------------

/*
13. Monthly Sales Trend

Query monthly total sales over the past year.
Display the sales trend, grouping by month, return current_month sale, last month sale
*/

SELECT 
    month,
    year,
    total_sales as current_month_sales,
    LAG(total_sales) OVER (ORDER BY year, month) as last_month_sales
FROM 
(
 SELECT 
     MONTH(o.order_date) AS month,
     YEAR(o.order_date) AS year,
     ROUND(SUM(oi.total_sales), 2) AS total_sales
 FROM orders as o
 JOIN order_items as oi
    ON o.order_id = oi.order_id
 GROUP BY 
     YEAR(o.order_date),
     MONTH(o.order_date)
) as monthly_sales
ORDER BY 
     year,
     month asc;

---------------------------------------------------------------------------

/*
14. Top Performing Sellers

Find the top 5 sellers based on total sales value.
Include both successful and failed orders, display their percentage of successful orders.
*/

WITH top_sellers as
(
	SELECT 
		 s.seller_id,
		 s.seller_name,
		 ROUND(SUM(oi.total_sales),2) as total_sales 
	FROM orders as o
	JOIN sellers as s
	ON o.seller_id = s.seller_id
	JOIN order_items as oi
	ON o.order_id = oi.order_id
	GROUP BY
		   s.seller_id,
		   s.seller_name
	ORDER BY 
		   total_sales desc
	LIMIT 5
),
seller_order_status as
(
	SELECT 
         ts.seller_id,
         ts.seller_name,
		 o.order_status,
		 count(*) as total_orders
	FROM orders as o
  JOIN top_sellers as ts
    ON o.seller_id = ts.seller_id
  WHERE order_status not in  ('Inprogress','Returned')
	GROUP BY 
		   ts.seller_id, 
       ts.seller_name,
       o.order_status
)

SELECT 
	seller_id,
    seller_name,
    SUM(total_orders) as total_orders,
    SUM(CASE 
            WHEN order_status = 'Completed' THEN total_orders
            ELSE 0
        END) as successful_orders,
    SUM(CASE 
            WHEN order_status = 'Cancelled' THEN total_orders
            ELSE 0
        END) as failed_orders,
     ROUND(SUM(
            CASE 
                WHEN order_status = 'Completed' THEN total_orders
                ELSE 0
            END) / SUM(total_orders) * 100,2) as successful_order_percentage
FROM seller_order_status
GROUP BY
	   seller_id,
	   seller_name
ORDER BY seller_id;

--------------------------------------------------------------------------
